server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          
        - id: vehicle-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/vehicles/**
          filters:
            - AuthenticationFilter
            
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**
          filters:
            - AuthenticationFilter

        - id: pricing-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/pricing/**
          filters:
            - AuthenticationFilter
            
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/payments/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
